### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by Yaffle** [peteroupc/BigNumber#3]
Hello, 
after testing of several BigInteger libs I found, that your implementation gives strange result for division sometimes:

```
  // (2**212 - 2**106) / (2**159 - 2**53 + 1)
  var s = new BigInteger("6582018229284824168619876730229320890292528855852623664389292032").divide(new BigInteger("730750818665451459101842416358132502628711530497")).toString();
  console.log(s === "9007199254740991"); // s should be equal to "9007199254740991", seems
```

**Comment by peteroupc** [comment]
I believe I've fixed it.  Try again now. (Note: Use `BigInteger.fromString` instead of `new BigInteger` to create a big integer from a decimal string.)
